<a href="https://colab.research.google.com/github/tsuli/Cognite/blob/main/X_data_download.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
#!pip install cognite-sdk
!pip install --upgrade cognite-sdk

Requirement already satisfied: cognite-sdk in /usr/local/lib/python3.7/dist-packages (2.39.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from cognite-sdk) (1.3.5)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /usr/local/lib/python3.7/dist-packages (from cognite-sdk) (2.23.0)
Requirement already satisfied: shapely==1.* in /usr/local/lib/python3.7/dist-packages (from cognite-sdk) (1.8.0)
Requirement already satisfied: geopandas==0.10.* in /usr/local/lib/python3.7/dist-packages (from cognite-sdk) (0.10.2)
Requirement already satisfied: requests-oauthlib==1.* in /usr/local/lib/python3.7/dist-packages (from cognite-sdk) (1.3.0)
Requirement already satisfied: pyproj>=2.2.0 in /usr/local/lib/python3.7/dist-packages (from geopandas==0.10.*->cognite-sdk) (3.2.1)
Requirement already satisfied: fiona>=1.8 in /usr/local/lib/python3.7/dist-packages (from geopandas==0.10.*->cognite-sdk) (1.8.20)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib==1.*->cognite-sdk) (3.1.1)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.10.*->cognite-sdk) (1.15.0)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.10.*->cognite-sdk) (1.1.1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.10.*->cognite-sdk) (0.7.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.10.*->cognite-sdk) (2021.10.8)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.10.*->cognite-sdk) (57.4.0)
Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.10.*->cognite-sdk) (7.1.2)
Requirement already satisfied: munch in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.10.*->cognite-sdk) (2.5.0)
Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas==0.10.*->cognite-sdk) (21.4.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->cognite-sdk) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->cognite-sdk) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->cognite-sdk) (1.19.5)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.21.0->cognite-sdk) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.21.0->cognite-sdk) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.21.0->cognite-sdk) (1.24.3)

In [38]:
%matplotlib inline

import os
from datetime import datetime, timedelta
from datetime import datetime
from getpass import getpass

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#from sklearn.ensemble import RandomForestRegressor
#from sklearn.linear_model import LinearRegression
#from sklearn.metrics import mean_squared_error
#from sklearn.metrics import r2_score

from cognite.client import CogniteClient

c = CogniteClient(api_key="NTgxY2MwMTItZjFmYS00N2U0LTgxNWEtZTcwZDNiMDU0OTFm",
                       project="publicdata", client_name="Tamas Suli")
# NTgxY2MwMTItZjFmYS00N2U0LTgxNWEtZTcwZDNiMDU0OTFm

In [39]:
predictors = pd.read_csv("predictors.csv") 
predictors.head()

                                               name               id externalId
0                          VAL_23-PDT-92501:X.Value    6190956317771  pi:160627
1     VAL_23-KA-9101-M01_OC_low stage_NOC3low:VALUE   25870989735584  pi:160252
2                     VAL_23_FIC_92543_02:Z.X.Value   54795035045033  pi:160031
3             VAL_23-LY-92529_SILch0_SC0_TYSP:VALUE   75873560338797  pi:160574
4  VAL_23-KA-9101-M01_Motor_Winding_Temp_Trip:VALUE  292999953190750  pi:160244

In [44]:
pred = predictors["id"].to_numpy()
pred

array([   6190956317771,   25870989735584,   54795035045033,
         75873560338797,  292999953190750,  338601415916476,
        384300500341710,  387441974987193,  536320806219501,
        562928045155242,  606890273743471,  622801209626283,
        814208809031578,  844472910348820,  868011656922238,
        881888156367988, 1076600623910780, 1106662769260200,
       1164067007934960, 1345316495294040, 1351428423647380,
       1450546190698360, 1524225545995910, 1571162867882370,
       1637590302537680, 1753079787159540, 1795193912485080,
       1831562938664240, 1883180660131040, 1926424373169200,
       2034273800491230, 2050783494697860, 2064237038699750,
       2076086075259770, 2098094490491930, 2197042193895250,
       2204690497640690, 2251496734604680, 2425058767259960,
       2689647540169170, 2782701856592840, 2852296688505310,
       2931306567219100, 2954069435092150, 2956179955417050,
       2962555707496210, 3263383236270380, 3318605425897630,
       3386754896121430, 3454716817729790, 3485477673418060,
       3527898561776830, 3559576717172910, 3677162631471540,
       3678764175994250, 3690887961236320, 3695151197573410,
       3770888999414160, 3849896371583010, 3935670095444470,
       3989201277369410, 4043338139372650, 4146236330407210,
       4469726646389560, 4491013851562230, 4574726276006650,
       4647026104475210, 4650870422672840, 4856059344406510,
       4919195407584130, 5018927156708960, 5028020536643750,
       5228965724544670, 5312516919536860, 5383396927147210,
       5467658596997840, 5556951711565880, 5614571190666290,
       5625449825540320, 5662453767080160, 5712835749078180,
       5827946607408090, 5869168734246680, 5928239598457580,
       6032397754677500, 6073209665887320, 6132322115531270,
       6134509923928990, 6148800802009500, 6152916819760100,
       6227120530180250, 6311713788427120, 6329427950060400,
       6386849649476680, 6421699458066670, 6446633289691910,
       6491937154066150, 6650939185704340, 6664190427142450,
       6702561940788020, 6721069432495270, 6730387952011380,
       6750894650523280, 6761834780597750, 6762334960704150,
       6908033636680650, 6954886684328040, 6999166665337180,
       7012228881452170, 7033189972515610, 7078273598364860,
       7093024427189810, 7106885005487180, 7145058854132320,
       7217876974598190, 7326685371667280, 7396519936470520,
       7411735241576770, 7481872987679420, 7514018008781840,
       7537279222393210, 7539061611330760, 7602320321174180,
       7631564664103110, 7683157899971860, 7746696627668690,
       7762903366268980, 7786205984185850, 7850077266067490,
       7857721200136110, 7986175887295490, 8030759143629460,
       8074905342471270, 8124424175096670, 8152209984966680,
       8301842998492860, 8337453484346430, 8378359481992420,
       8715462823345820, 8797197434176600, 8853721943046030,
       8854792084056400, 8877482139815950, 8891498171453960,
       8943362915100300, 9005999667357210])

In [25]:
dps = c.datapoints.retrieve(id=25870989735584, start="2w-ago", end="now")

In [ ]:
d = c.datapoints.retrieve(id=1076600623910780, start="2000d-ago", end="1901d-ago").to_pandas()

In [55]:
dps = c.datapoints.retrieve(id=[6190956317771,   25870989735584,   54795035045033,
         75873560338797,  292999953190750,  338601415916476,
        384300500341710,  387441974987193,  536320806219501,
        562928045155242,  606890273743471,  622801209626283,
        814208809031578,  844472910348820,  868011656922238,
        881888156367988, 1076600623910780, 1106662769260200,
       1164067007934960, 1345316495294040, 1351428423647380,
       1450546190698360, 1524225545995910, 1571162867882370,
       1637590302537680, 1753079787159540, 1795193912485080,
       1831562938664240, 1883180660131040, 1926424373169200,
       2034273800491230, 2050783494697860, 2064237038699750,
       2076086075259770, 2098094490491930, 2197042193895250,
       2204690497640690, 2251496734604680, 2425058767259960,
       2689647540169170, 2782701856592840, 2852296688505310,
       2931306567219100, 2954069435092150, 2956179955417050,
       2962555707496210, 3263383236270380, 3318605425897630,
       3386754896121430, 3454716817729790, 3485477673418060,
       3527898561776830, 3559576717172910, 3677162631471540,
       3678764175994250, 3690887961236320, 3695151197573410,
       3770888999414160, 3849896371583010, 3935670095444470,
       3989201277369410, 4043338139372650, 4146236330407210,
       4469726646389560, 4491013851562230, 4574726276006650,
       4647026104475210, 4650870422672840, 4856059344406510,
       4919195407584130, 5018927156708960, 5028020536643750,
       5228965724544670, 5312516919536860, 5383396927147210,
       5467658596997840, 5556951711565880, 5614571190666290,
       5625449825540320, 5662453767080160, 5712835749078180,
       5827946607408090, 5869168734246680, 5928239598457580,
       6032397754677500, 6073209665887320, 6132322115531270,
       6134509923928990, 6148800802009500, 6152916819760100,
       6227120530180250, 6311713788427120, 6329427950060400,
       6386849649476680, 6421699458066670, 6446633289691910,
       6491937154066150, 6650939185704340, 6664190427142450,
       6702561940788020, 6721069432495270, 6730387952011380,
       6750894650523280, 6761834780597750, 6762334960704150,
       6908033636680650, 6954886684328040, 6999166665337180,
       7012228881452170, 7033189972515610, 7078273598364860,
       7093024427189810, 7106885005487180, 7145058854132320,
       7217876974598190, 7326685371667280, 7396519936470520,
       7411735241576770, 7481872987679420, 7514018008781840,
       7537279222393210, 7539061611330760, 7602320321174180,
       7631564664103110, 7683157899971860, 7746696627668690,
       7762903366268980, 7786205984185850, 7850077266067490,
       7857721200136110, 7986175887295490, 8030759143629460,
       8074905342471270, 8124424175096670, 8152209984966680,
       8301842998492860, 8337453484346430, 8378359481992420,
       8715462823345820, 8797197434176600, 8853721943046030,
       8854792084056400, 8877482139815950, 8891498171453960,
       8943362915100300, 9005999667357210],
                            start="600d-ago",
                            end="1d-ago",
                            aggregates=["average"],
                            granularity="2d",
                            ignore_unknown_ids=True)
# 1076600623910780, 1106662769260200, 1345316495294040, 1450546190698360

In [56]:
dps

[<cognite.client.data_classes.datapoints.Datapoints object at 0x7fea6764d790>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea67949950>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea67949cd0>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea67949190>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea67949f90>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea67949790>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea67949450>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea67949ad0>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea67949750>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61e20110>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61e20dd0>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61e20c50>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61e20e90>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61e20210>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61e209d0>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61e20610>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61e20a50>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61e20090>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61afd050>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea67a71b50>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea6260d850>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61ea3cd0>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61ea3ed0>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea6274ca90>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea6766fa50>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea62741890>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea62741190>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea62741350>, <cognite.client.data_classes.datapoints.Datapoints object at 0x7fea61a11d10>]